import { getTotalImages, getTotalUsers } from "@/data-access/users";

export async function HeroStats() {
    const { totalImages, totalUsers } = await getStats(); 
  
    // Format numbers with commas
    const formatNumber = (num: number): string => {
      return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    };
  
    return (
      <p className="mt-4 text-lg text-muted-foreground">
        <span className="font-semibold text-primary">{formatNumber(totalImages)}</span> images generated by{" "}
        <span className="font-semibold text-primary">{formatNumber(totalUsers)}</span> happy users
      </p>
    );
  }

  export async function getStats() {
    try {
      const [totalImages, totalUsers] = await Promise.all([
        getTotalImages(),
        getTotalUsers()
      ]);
  
      return {
        totalImages,
        totalUsers,
      };
    } catch (error) {
      console.error('Error fetching stats:', error);
      return {
        totalImages: 0,
        totalUsers: 0,
      };
    }
  } 